django_app/app/accounts/urls.py
from django.urls import path
from .views import IndexView

app_name = "accounts"
urlpatterns = [
    path("", IndexView.as_view(), name="index"),
]

django_app/app/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from config.settings.dev import env

urlpatterns = [
    path("", include("accounts.urls")),
    path("admin/", admin.site.urls),
    path("silk/", include("silk.urls", namespace="silk")),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATICFILES_DIRS
    )
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += [
        path("silk/", include("silk.urls", namespace="silk")),
    ]

django_app/app/accounts/models.py
import uuid

from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser, PermissionsMixin
)
from django.db import models
from django.utils.translation import gettext_lazy as _


class CustomUserManager(BaseUserManager):

    def create_user(self, username, email, password=None):

        if not username:
            raise ValueError("Users must have a username.")

        user = self.model(
            username=username,
            email=self.normalize_email(email)
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, password=None):
        user = self.create_user(
            username=username,
            email=self.normalize_email(email),
            password=password
        )
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class CustomUser(AbstractBaseUser, PermissionsMixin):
    id = models.UUIDField(
        default=uuid.uuid4,
        primary_key=True,
        editable=False
    )
    username = models.CharField(
        verbose_name=_("username"),
        max_length=20,
        unique=True
    )
    email = models.EmailField(
        verbose_name=_("email address"),
        max_length=254,
        blank=True
    )
    is_active = models.BooleanField(
        verbose_name=_("active"),
        default=True
    )
    is_staff = models.BooleanField(
        verbose_name=_("admin"),
        default=False
    )

    objects = CustomUserManager()

    USERNAME_FIELD = "username"
    EMAIL_FIELD = "email"
    REQUIRED_FIELDS = ["email"]

    def __str__(self):
        return self.username

django_app/app/accounts/views.py
from django.views.generic import TemplateView


class IndexView(TemplateView):

    template_name = "accounts/index.html"

django_app/app/templates/accounts/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}トップ{% endblock title %}

{% block main %}

<h2 class="text-center my-5">サイトトップ</h2>

{% endblock main %}

django_app/app/templates/base.html
<!DOCTYPE html>

<html lang="ja">



    <head>

        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
        {% block css %}{% endblock css %}

        <title>{% block title %}{% endblock title %}</title>

    </head>



    <body>


        {% include 'snippets/header.html' %}


        <main class="container">

            {% block main %}{% endblock main %}
        
        </main>


        {% include 'snippets/footer.html' %}


        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
        <script src="https://kit.fontawesome.com/472bba83f0.js" crossorigin="anonymous"></script>
        {% block js %}{% endblock js %}

        
    </body>



</html>

django_app/app/templates/snippets/footer.html
<footer>
    <div class="text-center">
        <small class="text-dark">©2024 Example Inc. All rights reserved. </small>
    </div>
</footer>

django_app/app/templates/snippets/header.html
<header>
    <nav class="navbar navbar-light bg-light">
        <div class="container">
            <h1><a class="navbar-brand" href="{% url 'accounts:index' %}">Navbar</a></h1>
        </div>     
    </nav>
</header>

django_app/app/templates/snippets/pagination.html
<nav aria-label="Page navigation">

    <ul class="pagination justify-content-center">

        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
            </a>
        </li>
        {% endif %}

        {% for num in paginator.page_range %}
        {% if num <= page_obj.number|add:5 and num >= page_obj.number|add:-5 %}
            {% if page_obj.number == num %}
            <li class="page-item active">
                <span class="page-link">
                {{ num }}
                <span class="sr-only">(current)</span>
                </span>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
            </a>
        </li>
        {% endif %}

    </ul>

</nav>